[Setting, FEAT, Style]환경 셋팅, 레이아웃 분리, 기능 추가, UI 개선
TooNovel/TooNovel-FE pull request #8
Opened 2023-04-18 03:23 UTC by KIMDAHYUN98

### 📌 개발 개요

- resolve #1
- resolve #2 
- resolve #3 
- package.json에 dependency 의존성 추가
- header, footer, main 등 레이아웃 분리
  <br>

### 💻  작업 및 변경 사항
1. Prettier 관련 구성 파일 추가
2. infiniteScroll 의존성 추가
3. Post 관련 테스트 코드 추가
➡️ CommunityPage.vue : 전체 커뮤니티 글 조회
➡️ PostUpdate.vue : 커뮤니티 글 수정
➡️ PostWritePage.vue : 커뮤니티 글 작성
4. Work 관련 테스트 코드 추가
➡️ WorkViewPage.vue : 작품 전체 조회
5. proxy 코드 추가 : 백엔드와 통신을 위해 proxy 사용
6. Router 기능
➡️ PostWritePage.vue : 글 작성 페이지로 이동하는 라우터 추가
7. package.json에 eslint 관련 스크립트 추가
8. 메인페이지, Footer UI 개선

<br>

### ✅ Point
- 일부 페이지 화면 간단히 구성하겠습니다. (ex, 리뷰, 추천, 마이페이지 등)
- 메인페이지에 작품 리스트를 출력하는 작업 하겠습니다.
  <br>

2023-04-18 07:54 UTC, YJU-KimJeongSu requested changes

2023-04-18 07:54 UTC, YJU-KimJeongSu commented on src/views/PostUpdate.vue
> +          }).
JSON을 String으로 변환하고 헤더를 통해 다시 JSON으로 인식시키는 것은 불필요해보입니다.
axios는 자동으로 데이터를 인식하고 헤더를 달아주기 때문에
axios.post('/post/update', post).then ~~~ 형식이 깔끔하고 읽기 쉬운 코드인 것 같습니다

2023-04-18 07:54 UTC, YJU-KimJeongSu commented on src/views/PostUpdate.vue
PostUpdate.vue 파일에서 CheckStyle problems와 에러가 발견됩니다. 
또한 PostUpdate.vue로 넘어가는 링크가 보이지 않습니다.
테스트된 코드인지 확인 부탁드립니다. 의도적인 내용이면 코멘트 혹은 PR메시지로 작성 부탁드립니다.

2023-04-18 07:54 UTC, YJU-KimJeongSu commented on vue.config.js
> +      }
개발 버전이어서 환경 변수가 아니라 직접 하드코딩을 하신 것으로 보입니다.
개발 단계여도 추후에 실수로 노출되는 것을 방지하고 통합적으로 관리하기 위해 dotenv를 사용해주세요.

2023-04-18 07:54 UTC, YJU-KimJeongSu commented on src/components/AllProductList.vue
> +<style>
App.vue를 제외한 모든 <style> 태그에는 scoped를 추가해주세요.
당장은 눈에 보이지 않더라도 추후에 컴포넌트를 여러개 적용하게 되면 충돌이 일어날 위험이 큽니다.
CommunityPage.vue / WorkViewPage.vue / MainPage.vue 파일에서도 같은 문제가 있습니다.

2023-04-19 05:43 UTC, YJU-KimJeongSu commented
이번 스프린트 일정에 리팩토링이 포함되어 있으므로
1. 필요없는 코드 (ex: methods: {}, ...)
2. 디렉토리 구성 (Page와 Component가 구분이 안된 문제)
3. 코드 스타일 통합 (axios의 JSON 전달 방법)
을 위한 이슈 작성하겠습니다

2023-04-19 11:00 UTC, KIMDAHYUN98 commented on src/views/PostUpdate.vue
해당 파일은 테스트를 위한 페이지인 것 같습니다.

2023-04-19 11:05 UTC, YJU-KimJeongSu commented on src/views/PostUpdate.vue
테스트 코드 작성 중 이상한 파일이 잘못 들어간 것으로 확인됐습니다. 삭제 후 push부탁드립니다

2023-04-19 11:48 UTC, YJU-KimJeongSu reviewed
전체적으로 훨씬 정리된 느낌이 납니다. 이정도면 괜찮을 것 같습니다! 수고하셨습니당

2023-04-19 11:48 UTC, YJU-KimJeongSu commented on src/views/AllProductList.vue
> +    const URL = "https://aee2de78-332d-40e2-af1e-ee62eb99672d.mock.pstmn.io";
테스트 주소인 것 같습니다. 보안상 문제는 없지만 팀원은 활용 못하니 천천히 env를 이용한 서버 주소로 변경하겠습니다.

2023-04-19 11:48 UTC, YJU-KimJeongSu commented on src/views/LoginPage.vue
>  };
리팩토링할 때 삭제하려고 했던 부분을 미리 삭제해주셨군요. 감사합니다.
다만 data() { return {}; }도 지워야하는 부분인데 제가 이전 코멘트에서 생략한 탓에 그대로 남겨두신 것 같네요.
리팩토링 이슈에 이미 포함된 내용이니 다시 수정 안해주셔도 될 것 같습니다.

2023-04-20 01:09 UTC, merged